name: sighttrack
description: "An environment and biodiversity monitoring app"
publish_to: 'none'

version: 3.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Amplify dependencies
  amplify_flutter: ^2.6.1
  amplify_auth_cognito: ^2.6.1
  amplify_storage_s3: ^2.6.1
  amplify_api: ^2.6.1
  amplify_datastore: ^2.6.1
  amplify_authenticator: ^2.3.3
  aws_lambda_api: ^2.0.0

  logging: ^1.3.0
  persistent_bottom_nav_bar: ^6.2.1
  mapbox_maps_flutter: ^2.6.1
  geolocator: ^13.0.3
  image_picker: ^1.1.2
  intl: ^0.19.0
  camera: ^0.11.1
  permission_handler: ^11.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - "assets/logo.jpg"